### ISSUE TITLE
Change the Header Logo 

### ISSUE THREAD

**Issue by sayantan1413** [sayantan1413/Postagram#13]
Currently there is an instagram logo in the header. But now replace that logo with this logo and maintain the aspect ratio. Here is the link for the new logo.

https://drive.google.com/file/d/1vZ9zvGMooDihrRYlz-5QGZX7jJdB62sE/view?usp=sharing

**Comment by DelayCoderz** [comment]
assign me pls @sayantan1413

**Comment by sayantan1413** [comment]
Go ahead @DelayCoderz !!
