### ISSUE TITLE
Position the option dots to the right

### ISSUE THREAD

**Issue by debjani1413** [sayantan1413/Postagram#5]
The option dots are placed just after the username.
![dot](https://user-images.githubusercontent.com/65902742/135995580-708eb0dc-8e10-4d0c-867f-c471cba4791f.PNG)
Add spacing before them so they can be positioned on the right side.

**Comment by irfanukani** [comment]
Hi, can i work on this issue?

**Comment by debjani1413** [comment]
Great work 🎉 Welcome to our project btw🎉 @irfanukani

**Comment by irfanukani** [comment]
Thank you. Kindly, merge the pull requests that i did if it validates the contribution rules.
